services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: hyac_mongodb
    hostname: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_USER: ${MONGODB_USERNAME}
      MONGODB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - hyac_network
    healthcheck:
      test: |
        mongosh --host localhost --port 27017 \
          --authenticationDatabase admin \
          -u "${MONGODB_USERNAME}" -p "${MONGODB_PASSWORD}" \
          --eval "if (db.isMaster().ismaster) { quit(0); } else { quit(1); }"
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 15s
  minio:
    image: bitnami/minio:latest
    container_name: hyac_minio
    restart: unless-stopped
    ports:
    - 9000:9000
    - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_SERVER_URL: "https://oss.${DOMAIN_NAME}"
      MINIO_SCHEME: 'https'
      MINIO_BROWSER: "off" # if you want to use minio console please modify to on
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - minio_data:/data
    networks:
    - hyac_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hyac-minio.rule=Host(`oss.${DOMAIN_NAME}`)"
      - "traefik.http.routers.hyac-minio.entrypoints=websecure"
      - "traefik.http.routers.hyac-minio.tls.certresolver=myresolver"
      - "traefik.http.services.hyac-minio.loadbalancer.server.port=9000"
      - "traefik.http.services.hyac-minio.loadbalancer.passhostheader=true"
  traefik:
    image: "traefik:v3.5.0"
    container_name: "hyac_traefik"
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL_ADDRESS}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/dynamic:/etc/traefik/dynamic"
    networks:
      - hyac_network
  server:
    build:
      context: ./server
    image: wicos/hyac_server:${SERVER_IMAGE_TAG:-latest}
    container_name: hyac_server
    restart: unless-stopped
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      DEV_MODE: "false"
      APP_CODE_PATH_ON_HOST: ${APP_CODE_PATH_ON_HOST}
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik/dynamic:/traefik/dynamic
    networks:
    - hyac_network
    healthcheck:
      test: ["CMD", "python", "/server/healthcheck.py"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hyac-server.rule=Host(`server.${DOMAIN_NAME}`)"
      - "traefik.http.routers.hyac-server.entrypoints=websecure"
      - "traefik.http.routers.hyac-server.tls.certresolver=myresolver"
      - "traefik.http.services.hyac-server.loadbalancer.server.port=8000"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: wicos/hyac_web:${WEB_IMAGE_TAG:-latest}
    container_name: hyac_web
    restart: unless-stopped
    environment:
      VITE_SERVICE_BASE_URL: "https://server.${DOMAIN_NAME}"
    networks:
      - hyac_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hyac-web.rule=Host(`console.${DOMAIN_NAME}`)"
      - "traefik.http.routers.hyac-web.entrypoints=websecure"
      - "traefik.http.routers.hyac-web.tls.certresolver=myresolver"
      - "traefik.http.services.hyac-web.loadbalancer.server.port=80"
      - "traefik.http.services.hyac-web.loadbalancer.passhostheader=true"
  lsp:
    build:
      context: ./lsp
      dockerfile: Dockerfile
    image: wicos/hyac_lsp:${LSP_IMAGE_TAG:-latest}
    container_name: hyac_lsp
    restart: unless-stopped
    networks:
      - hyac_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hyac-lsp.rule=Host(`lsp.${DOMAIN_NAME}`)"
      - "traefik.http.routers.hyac-lsp.entrypoints=websecure"
      - "traefik.http.routers.hyac-lsp.tls.certresolver=myresolver"
      - "traefik.http.routers.hyac-lsp.service=hyac-lsp"
      - "traefik.http.services.hyac-lsp.loadbalancer.server.port=8765"
      - "traefik.http.routers.hyac-lsp.middlewares=hyac-lsp-ws"
      - "traefik.http.middlewares.hyac-lsp-ws.headers.customrequestheaders.X-Forwarded-Proto=https"
  app:
    build:
      context: ./app
    image: wicos/hyac_app:${APP_IMAGE_TAG:-latest}
    command: ["echo", "Hyac App image built. This container does not need to run."]
    restart: "no"
    networks:
      - hyac_network

networks:
  hyac_network:
    driver: bridge
volumes:
  mongodb_data:
    driver: local
  minio_data:
    driver: local
