services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: hyac_mongodb
    hostname: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_USER: ${MONGODB_USERNAME}
      MONGODB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - hyac_network
    healthcheck:
      test: |
        mongosh --host localhost --port 27017 \
          --authenticationDatabase admin \
          -u "${MONGODB_ROOT_USER}" -p "${MONGODB_ROOT_PASSWORD}" \
          --eval "if (db.isMaster().ismaster) { quit(0); } else { quit(1); }"
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 15s
  minio:
    image: bitnami/minio:latest
    container_name: hyac_minio
    restart: unless-stopped
    ports:
    - 9000:9000
    - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
    - minio_data:/data
    networks:
    - hyac_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: hyac_nginx
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${EMAIL_ADDRESS}
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/user_conf.d:ro
    - ./nginx/certs:/etc/letsencrypt
    depends_on:
    - server
    networks:
    - hyac_network
  server:
    image: wicos/hyac_server:latest
    container_name: hyac_server
    restart: unless-stopped
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      DEV_MODE: ${DEV_MODE}
      APP_CODE_PATH_ON_HOST: ${APP_CODE_PATH_ON_HOST}
    ports:
      - 8000:8000
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./nginx/conf.d:/nginx/conf.d
    networks:
    - hyac_network
    healthcheck:
      test: ["CMD", "python", "/server/healthcheck.py"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
  app:
    image: wicos/hyac_app:latest
    command: ["echo", "This container is for image pulling and should not be running."]
  uploader:
    image: wicos/hyac_uploader:latest
    container_name: hyac_uploader
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - BUILD=${WEB_BUILD}
    networks:
      - hyac_network
    depends_on:
      server:
        condition: service_healthy
    restart: "no"

networks:
  hyac_network:
    driver: bridge
volumes:
  mongodb_data:
    driver: local
  minio_data:
    driver: local
