/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'apps',
    path: '/apps',
    component: 'layout.base$view.apps',
    meta: {
      title: 'apps',
      i18nKey: 'route.apps',
      fixedIndexInTab: 0,
      icon: 'router-board',
      localIcon: 'router-board',
      order: 0
    },
    props: true
  },
  {
    name: 'database',
    path: '/database',
    component: 'layout.base$view.database',
    meta: {
      title: 'database',
      i18nKey: 'route.database',
      icon: 'router-database',
      localIcon: 'router-database',
      order: 2,
      keepAlive: true
    }
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base$view.function',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'router-function',
      localIcon: 'router-function',
      order: 1,
      keepAlive: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.blank$view.home',
    props: true,
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      constant: false,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base$view.log',
    meta: {
      title: 'log',
      i18nKey: 'route.log',
      icon: 'router-logs',
      localIcon: 'router-logs',
      order: 4
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'setting',
    path: '/setting',
    component: 'layout.base$view.setting',
    meta: {
      title: 'setting',
      i18nKey: 'route.setting',
      icon: 'router-setting',
      localIcon: 'router-setting',
      order: 5
    }
  },
  {
    name: 'storage',
    path: '/storage',
    component: 'layout.base$view.storage',
    meta: {
      title: 'storage',
      i18nKey: 'route.storage',
      icon: 'router-goods',
      localIcon: 'router-goods',
      order: 3,
      keepAlive: true
    }
  }
];
